name: Sample Workflow
on:
  push:
    branches: [ master ]
    paths:
            - 'force-app/**'
  pull_request:
    branches: [ master ]
    paths:
            - 'force-app/**'         

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event_name == 'push'
    - uses: actions/setup-node@v1
      with:
        node-version: '>=14'
        check-latest: true
   
    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core

        
    - name: Deploy source
      id: Deploy
      if: github.event_name == 'push'
      run:
        node_modules/sfdx-cli/bin/run force:source:deploy --manifest LRQA --json --loglevel fatal
